# Generated by Django 3.2.13 on 2022-11-23 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ToDo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(editable=False, max_length=100)),
                ('description', models.TextField(max_length=1000)),
                ('due_date', models.DateField(blank=True)),
                ('tags', models.CharField(max_length=1000)),
                ('status', models.CharField(choices=[('1', 'OPEN'), ('2', 'WORKING'), ('3', 'DONE'), ('4', 'OVERDUE')], default='1', max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
