# Generated by Django 3.2.13 on 2022-11-23 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_todo_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='todo',
            name='tags',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tags'),
        ),
    ]
