# Generated by Django 3.2.13 on 2022-11-23 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0004_auto_20221123_1156'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ToDo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=1000)),
                ('due_date', models.DateField(blank=True)),
                ('status', models.CharField(choices=[('1', 'OPEN'), ('2', 'WORKING'), ('3', 'DONE'), ('4', 'OVERDUE')], default='1', max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('tags', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tags')),
            ],
        ),
    ]
