# Generated by Django 3.2.13 on 2022-11-23 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_tags_todo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='tags',
        ),
        migrations.AddField(
            model_name='todo',
            name='tags',
            field=models.ManyToManyField(to='app.Tags'),
        ),
    ]
