# Generated by Django 3.2.13 on 2022-11-23 06:49

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20221123_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='due_date',
            field=models.DateField(blank=True, validators=[app.models.validate_due_date]),
        ),
    ]
